const birds = [
  { en: "Hazel Grouse", jp: "エゾライチョウ" },
  { en: "Japanese Quail", jp: "ウズラ" },
  { en: "Copper Pheasant", jp: "ヤマドリ" },
  { en: "Common Pheasant", jp: "キジ" },
  { en: "Taiga Bean Goose", jp: "ヒシクイ" },
  { en: "Greater White-fronted Goose", jp: "マガン" },
  { en: "Tundra Swan", jp: "コハクチョウ" },
  { en: "Whooper Swan", jp: "オオハクチョウ" },
  { en: "Mandarin Duck", jp: "オシドリ" },
  { en: "Eurasian Wigeon", jp: "ヒドリガモ" },
  { en: "Mallard", jp: "マガモ" },
  { en: "Eastern Spot-billed Duck", jp: "カルガモ" },
  { en: "Northern Shoveler", jp: "ハシビロガモ" },
  { en: "Northern Pintail", jp: "オナガガモ" },
  { en: "Eurasian Teal", jp: "コガモ" },
  { en: "Harlequin Duck", jp: "シノリガモ" },
  { en: "Black Scoter", jp: "クロガモ" },
  { en: "Long-tailed Duck", jp: "コオリガモ" },
  { en: "Common Goldeneye", jp: "ホオジロガモ" },
  { en: "Red-breasted Merganser", jp: "ウミアイサ" },
  { en: "Little Grebe", jp: "カイツブリ" },
  { en: "Red-necked Grebe", jp: "アカエリカイツブリ" },
  { en: "Great Crested Grebe", jp: "カンムリカイツブリ" },
  { en: "Black-necked Grebe", jp: "ハジロカイツブリ" },
  { en: "Japanese Wood Pigeon", jp: "カラスバト" },
  { en: "Oriental Turtle Dove", jp: "キジバト" },
  { en: "Common Emerald Dove", jp: "キンバト" },
  { en: "White-bellied Green Pigeon", jp: "アオバト" },
  { en: "Whistling Green Pigeon", jp: "ズアカアオバト" },
  { en: "Pacific Loon", jp: "シロエリオオハム" },
  { en: "Streaked Shearwater", jp: "オオミズナギドリ" },
  { en: "Great Cormorant", jp: "カワウ" },
  { en: "Japanese Cormorant", jp: "ウミウ" },
  { en: "Eurasian Bittern", jp: "サンカノゴイ" },
  { en: "Yellow Bittern", jp: "ヨシゴイ" },
  { en: "Japanese Night Heron", jp: "ミゾゴイ" },
  { en: "Black-crowned Night Heron", jp: "ゴイサギ" },
  { en: "Striated Heron", jp: "ササゴイ" },
  { en: "Grey Heron", jp: "アオサギ" },
  { en: "Great Egret", jp: "ダイサギ" },
  { en: "Little Egret", jp: "コサギ" },
  { en: "White-naped Crane", jp: "マナヅル" },
  { en: "Red-crowned Crane", jp: "タンチョウ" },
  { en: "Hooded Crane", jp: "ナベヅル" },
  { en: "Water Rail", jp: "クイナ" },
  { en: "White-breasted Waterhen", jp: "シロハラクイナ" },
  { en: "Ruddy-breasted Crake", jp: "ヒクイナ" },
  { en: "Common Moorhen", jp: "バン" },
  { en: "Eurasian Coot", jp: "オオバン" },
  { en: "Rufous Hawk-Cuckoo", jp: "ジュウイチ" },
  { en: "Lesser Cuckoo", jp: "ホトトギス" },
  { en: "Indian Cuckoo", jp: "セグロカッコウ" },
  { en: "Oriental Cuckoo", jp: "ツツドリ" },
  { en: "Common Cuckoo", jp: "カッコウ" },
  { en: "Jungle Nightjar", jp: "ヨタカ" },
  { en: "White-throated Needletail", jp: "ハリオアマツバメ" },
  { en: "Pacific Swift", jp: "アマツバメ" },
  { en: "Northern Lapwing", jp: "タゲリ" },
  { en: "Grey-headed Lapwing", jp: "ケリ" },
  { en: "Pacific Golden Plover", jp: "ムナグロ" },
  { en: "Long-billed Plover", jp: "イカルチドリ" },
  { en: "Little Ringed Plover", jp: "コチドリ" },
  { en: "Kentish Plover", jp: "シロチドリ" },
  { en: "Lesser Sand Plover", jp: "メダイチドリ" },
  { en: "Eurasian Oystercatcher", jp: "ミヤコドリ" },
  { en: "Eurasian Woodcock", jp: "ヤマシギ" },
  { en: "Amami Woodcock", jp: "アマミヤマシギ" },
  { en: "Latham's Snipe", jp: "オオジシギ" },
  { en: "Common Snipe", jp: "タシギ" },
  { en: "Whimbrel", jp: "チュウシャクシギ" },
  { en: "Eastern Curlew", jp: "ホウロクシギ" },
  { en: "Spotted Redshank", jp: "ツルシギ" },
  { en: "Common Redshank", jp: "アカアシシギ" },
  { en: "Marsh Sandpiper", jp: "コアオアシシギ" },
  { en: "Green Sandpiper", jp: "クサシギ" },
  { en: "Wood Sandpiper", jp: "タカブシギ" },
  { en: "Grey-tailed Tattler", jp: "キアシシギ" },
  { en: "Terek Sandpiper", jp: "ソリハシシギ" },
  { en: "Common Sandpiper", jp: "イソシギ" },
  { en: "Ruddy Turnstone", jp: "キョウジョシギ" },
  { en: "Red-necked Stint", jp: "トウネン" },
  { en: "Dunlin", jp: "ハマシギ" },
  { en: "Greater Painted-snipe", jp: "タマシギ" },
  { en: "Oriental Pratincole", jp: "ツバメチドリ" },
  { en: "Black-headed Gull", jp: "ユリカモメ" },
  { en: "Saunders's Gull", jp: "ズグロカモメ" },
  { en: "Black-tailed Gull", jp: "ウミネコ" },
  { en: "Glaucous-winged Gull", jp: "ワシカモメ" },
  { en: "European Herring Gull", jp: "セグロカモメ" },
  { en: "Slaty-backed Gull", jp: "オオセグロカモメ" },
  { en: "Little Tern", jp: "コアジサシ" },
  { en: "Western Osprey", jp: "ミサゴ" },
  { en: "Black Kite", jp: "トビ" },
  { en: "White-tailed Eagle", jp: "オジロワシ" },
  { en: "Steller's Sea Eagle", jp: "オオワシ" },
  { en: "Crested Serpent Eagle", jp: "カンムリワシ" },
  { en: "Eastern Marsh Harrier", jp: "チュウヒ" },
  { en: "Japanese Sparrowhawk", jp: "ツミ" },
  { en: "Northern Goshawk", jp: "オオタカ" },
  { en: "Grey-faced Buzzard", jp: "サシバ" },
  { en: "Common Buzzard", jp: "ノスリ" },
  { en: "Mountain Hawk-Eagle", jp: "クマタカ" },
  { en: "Sunda Scops Owl", jp: "オオコノハズク" },
  { en: "Oriental Scops Owl", jp: "コノハズク" },
  { en: "Ryukyu Scops Owl", jp: "リュウキュウコノハズク" },
  { en: "Ural Owl", jp: "フクロウ" },
  { en: "Brown Hawk-Owl", jp: "アオバズク" },
  { en: "Long-eared Owl", jp: "トラフズク" },
  { en: "Ruddy Kingfisher", jp: "アカショウビン" },
  { en: "Common Kingfisher", jp: "カワセミ" },
  { en: "Crested Kingfisher", jp: "ヤマセミ" },
  { en: "Oriental Dollarbird", jp: "ブッポウソウ" },
  { en: "Eurasian Wryneck", jp: "アリスイ" },
  { en: "Japanese Pygmy Woodpecker", jp: "コゲラ" },
  { en: "White-backed Woodpecker", jp: "オオアカゲラ" },
  { en: "Great Spotted Woodpecker", jp: "アカゲラ" },
  { en: "Black Woodpecker", jp: "クマゲラ" },
  { en: "Japanese Green Woodpecker", jp: "アオゲラ" },
  { en: "Grey-headed Woodpecker", jp: "ヤマゲラ" },
  { en: "Okinawa Woodpecker", jp: "ノグチゲラ" },
  { en: "Common Kestrel", jp: "チョウゲンボウ" },
  { en: "Eurasian Hobby", jp: "チゴハヤブサ" },
  { en: "Peregrine Falcon", jp: "ハヤブサ" },
  { en: "Fairy Pitta", jp: "ヤイロチョウ" },
  { en: "Ashy Minivet", jp: "サンショウクイ" },
  { en: "Japanese Paradise Flycatcher", jp: "サンコウチョウ" },
  { en: "Bull-headed Shrike", jp: "モズ" },
  { en: "Eurasian Jay", jp: "カケス" },
  { en: "Lidth's Jay", jp: "ルリカケス" },
  { en: "Azure-winged Magpie", jp: "オナガ" },
  { en: "Daurian Jackdaw", jp: "コクマルガラス" },
  { en: "Rook", jp: "ミヤマガラス" },
  { en: "Carrion Crow", jp: "ハシボソガラス" },
  { en: "Large-billed Crow", jp: "ハシブトガラス" },
  { en: "Goldcrest", jp: "キクイタダキ" },
  { en: "Marsh Tit", jp: "ハシブトガラ" },
  { en: "Willow Tit", jp: "コガラ" },
  { en: "Varied Tit", jp: "ヤマガラ" },
  { en: "Coal Tit", jp: "ヒガラ" },
  { en: "Japanese Tit", jp: "シジュウカラ" },
  { en: "Eurasian Skylark", jp: "ヒバリ" },
  { en: "Barn Swallow", jp: "ツバメ" },
  { en: "Pacific Swallow", jp: "リュウキュウツバメ" },
  { en: "Red-rumped Swallow", jp: "コシアカツバメ" },
  { en: "Asian House Martin", jp: "イワツバメ" },
  { en: "Brown-eared Bulbul", jp: "ヒヨドリ" },
  { en: "Japanese Bush Warbler", jp: "ウグイス" },
  { en: "Asian Stubtail", jp: "ヤブサメ" },
  { en: "Long-tailed Tit", jp: "エナガ" },
  { en: "Kamchatka Leaf Warbler", jp: "オオムシクイ" },
  { en: "Japanese Leaf Warbler", jp: "メボソムシクイ" },
  { en: "Sakhalin Leaf Warbler", jp: "エゾムシクイ" },
  { en: "Eastern Crowned Warbler", jp: "センダイムシクイ" },
  { en: "Bonin White-eye", jp: "メグロ" },
  { en: "Lanceolated Warbler", jp: "マキノセンニュウ" },
  { en: "Middendorff's Grasshopper Warbler", jp: "シマセンニュウ" },
  { en: "Styan's Grasshopper Warbler", jp: "ウチヤマセンニュウ" },
  { en: "Marsh Grassbird", jp: "オオセッカ" },
  { en: "Gray's Grasshopper Warbler", jp: "エゾセンニュウ" },
  { en: "Oriental Reed Warbler", jp: "オオヨシキリ" },
  { en: "Black-browed Reed Warbler", jp: "コヨシキリ" },
  { en: "Zitting Cisticola", jp: "セッカ" },
  { en: "Japanese Waxwing", jp: "ヒレンジャク" },
  { en: "Eurasian Nuthatch", jp: "ゴジュウカラ" },
  { en: "Eurasian Treecreeper", jp: "キバシリ" },
  { en: "Eurasian Wren", jp: "ミソサザイ" },
  { en: "White-cheeked Starling", jp: "ムクドリ" },
  { en: "Chestnut-cheeked Starling", jp: "コムクドリ" },
  { en: "Brown Dipper", jp: "カワガラス" },
  { en: "Siberian Thrush", jp: "マミジロ" },
  { en: "Scaly Thrush", jp: "トラツグミ" },
  { en: "Japanese Thrush", jp: "クロツグミ" },
  { en: "Eyebrowed Thrush", jp: "マミチャジナイ" },
  { en: "Pale Thrush", jp: "シロハラ" },
  { en: "Brown-headed Thrush", jp: "アカハラ" },
  { en: "Naumann's Thrush", jp: "ツグミ" },
  { en: "Japanese Robin", jp: "コマドリ" },
  { en: "Ryukyu Robin", jp: "アカヒゲ" },
  { en: "Siberian Rubythroat", jp: "ノゴマ" },
  { en: "Siberian Blue Robin", jp: "コルリ" },
  { en: "Red-flanked Bluetail", jp: "ルリビタキ" },
  { en: "Daurian Redstart", jp: "ジョウビタキ" },
  { en: "African Stonechat", jp: "ノビタキ" },
  { en: "Blue Rock Thrush", jp: "イソヒヨドリ" },
  { en: "Grey-streaked Flycatcher", jp: "エゾビタキ" },
  { en: "Dark-sided Flycatcher", jp: "サメビタキ" },
  { en: "Asian Brown Flycatcher", jp: "コサメビタキ" },
  { en: "Narcissus Flycatcher", jp: "キビタキ" },
  { en: "Mugimaki Flycatcher", jp: "ムギマキ" },
  { en: "Taiga Flycatcher", jp: "オジロビタキ" },
  { en: "Blue-and-white Flycatcher", jp: "オオルリ" },
  { en: "Japanese Accentor", jp: "カヤクグリ" },
  { en: "Russet Sparrow", jp: "ニュウナイスズメ" },
  { en: "Eurasian Tree Sparrow", jp: "スズメ" },
  { en: "Western Yellow Wagtail", jp: "ツメナガセキレイ" },
  { en: "Grey Wagtail", jp: "キセキレイ" },
  { en: "White Wagtail", jp: "ハクセキレイ" },
  { en: "Japanese Wagtail", jp: "セグロセキレイ" },
  { en: "Richard's Pipit", jp: "マミジロタヒバリ" },
  { en: "Olive-backed Pipit", jp: "ビンズイ" },
  { en: "Buff-bellied Pipit", jp: "タヒバリ" },
  { en: "Brambling", jp: "アトリ" },
  { en: "Grey-capped Greenfinch", jp: "カワラヒワ" },
  { en: "Eurasian Siskin", jp: "マヒワ" },
  { en: "Common Redpoll", jp: "ベニヒワ" },
  { en: "Asian Rosy Finch", jp: "ハギマシコ" },
  { en: "Long-tailed Rosefinch", jp: "ベニマシコ" },
  { en: "Common Rosefinch", jp: "アカマシコ" },
  { en: "Pallas's Rosefinch", jp: "オオマシコ" },
  { en: "Red Crossbill", jp: "イスカ" },
  { en: "Two-barred Crossbill", jp: "ナキイスカ" },
  { en: "Eurasian Bullfinch", jp: "ウソ" },
  { en: "Hawfinch", jp: "シメ" },
  { en: "Japanese Grosbeak", jp: "イカル" },
  { en: "Lapland Longspur", jp: "ツメナガホオジロ" },
  { en: "Meadow Bunting", jp: "ホオジロ" },
  { en: "Chestnut-eared Bunting", jp: "ホオアカ" },
  { en: "Rustic Bunting", jp: "カシラダカ" },
  { en: "Yellow-throated Bunting", jp: "ミヤマホオジロ" },
  { en: "Yellow-breasted Bunting", jp: "シマアオジ" },
  { en: "Yellow Bunting", jp: "ノジコ" },
  { en: "Black-faced Bunting", jp: "アオジ" },
  { en: "Grey Bunting", jp: "クロジ" },
  { en: "Japanese Reed Bunting", jp: "コジュリン" },
  { en: "Common Reed Bunting", jp: "オオジュリン" },
  { en: "Chinese Bamboo Partridge", jp: "コジュケイ" },
  { en: "Chinese Hwamei", jp: "ガビチョウ" },
  { en: "Crested Myna", jp: "ハッカチョウ" },
  { en: "Eurasian Collared Dove", jp: "シラコバト" },
  { en: "Eurasian Magpie", jp: "カササギ" },
  { en: "Japanese White-eye", jp: "メジロ" },
  { en: "Masked Laughingthrush", jp: "カオグロガビチョウ" },
  { en: "Mute Swan", jp: "コブハクチョウ" },
  { en: "Oriental Stork", jp: "コウノトリ" },
  { en: "Red-billed Leiothrix", jp: "ソウシチョウ" },
  { en: "Rock Dove", jp: "ドバト" },
  { en: "Rose-ringed Parakeet", jp: "ホンセイインコ" },
  { en: "White-browed Laughingthrush", jp: "カオジロガビチョウ" },
];

module.exports = birds;
